title: "Foundations of Machine Learning"
description: "Notes for Foundations of Machine Learning"
theme: minima

include:
  - _chapters

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap